import Head from "next/head";
import styles from "@/styles/Home.module.css";
import { blocks } from "@/templates/index.template";
import dynamic from "next/dynamic";

export default function Home({ blocks }: any) {
  console.log("blocks", blocks);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="https://rsms.me/inter/inter.css" />
      </Head>
      <main className={styles.main}>
        {blocks.map((block: any) => {
          const BlockComponent = dynamic(
            () => import(`@/components/${block.type}/${block.type}.component`)
          );
          return <BlockComponent key={block.id} {...block.data} />;
        })}
      </main>
    </>
  );
}

export async function getStaticProps() {
  return {
    props: {
      blocks,
    },
  };
}
